# Generated by Django 6.1.1 on 2026-10-04 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def recover_trip_statuses(apps, schema_editor):
    Trip = apps.get_model('core', 'Trip')
    Trip.objects.filter(drop_off_time__isnull=False).update(status='COMPLETED')
    Trip.objects.filter(drop_off_time__isnull=True, driver__isnull=False).update(status='ASSIGNED')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_driver_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PANIC', 'Panic'), ('PULLED_OVER', 'Pulled over'), ('ACCIDENT', 'Accident'), ('BREAKDOWN', 'Breakdown'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.RunPython(recover_trip_statuses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('driver',), name='one_open_shift_per_driver'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('vehicle',), name='one_open_shift_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ASSIGNED', 'IN_PROGRESS'])), fields=('driver',), name='one_active_trip_per_driver'),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_alerts', to='core.driver'),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
