# Generated by Django 6.1.1 on 2026-10-04 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_safetyalert_trip_cancellation_reason_trip_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(help_text='Horizontal accuracy in metres.')),
                ('heading', models.FloatField(blank=True, help_text='Degrees clockwise from true north.', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Metres per second.', null=True)),
                ('timestamp', models.DateTimeField(help_text='Device location-fix time, not upload time.')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='latest_location', to='core.shift')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='gps_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='gps_longitude_range'), models.CheckConstraint(condition=models.Q(('accuracy__gte', 0)), name='gps_accuracy_nonnegative'), models.CheckConstraint(condition=models.Q(('heading__isnull', True), models.Q(('heading__gte', 0), ('heading__lt', 360)), _connector='OR'), name='gps_heading_range'), models.CheckConstraint(condition=models.Q(('speed__isnull', True), ('speed__gte', 0), _connector='OR'), name='gps_speed_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TRIP_ASSIGNED', 'Trip assigned'), ('SAFETY_ALERT', 'Safety alert')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('PENDING_APNS_INTEGRATION', 'Pending APNs integration')], default='PENDING_APNS_INTEGRATION', max_length=30)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_events', to=settings.AUTH_USER_MODEL)),
                ('safety_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_events', to='core.safetyalert')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_events', to='core.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'status', 'created_at'], name='notification_pending_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'TRIP_ASSIGNED'), ('safety_alert__isnull', True), ('trip__isnull', False)), models.Q(('kind', 'SAFETY_ALERT'), ('safety_alert__isnull', False), ('trip__isnull', True)), _connector='OR'), name='notification_has_matching_subject'), models.CheckConstraint(condition=models.Q(('status', 'PENDING_APNS_INTEGRATION')), name='notification_pending_integration_only'), models.UniqueConstraint(fields=('recipient', 'kind', 'trip'), name='one_trip_event_per_recipient'), models.UniqueConstraint(fields=('recipient', 'kind', 'safety_alert'), name='one_alert_event_per_recipient')],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.UUIDField(help_text='Random UUID generated and persisted by the native app.')),
                ('apns_token', models.CharField(help_text='Hexadecimal APNs device token; treat as sensitive data.', max_length=512)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=10)),
                ('topic', models.CharField(help_text='Allowed app bundle identifier / APNs topic.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'installation_id', 'environment', 'topic'), name='device_per_account_installation'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('installation_id', 'environment', 'topic'), name='one_active_installation_owner'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('apns_token', 'environment', 'topic'), name='one_active_apns_token_owner')],
            },
        ),
    ]
