# Generated by Django 6.1.1 on 2026-10-04 19:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mobile_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='STARTED', max_length=24)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('provider_apns_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_revision', models.PositiveIntegerField()),
                ('apns_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=24)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='notificationevent',
            name='notification_pending_integration_only',
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='status',
            field=models.CharField(choices=[('PENDING_APNS_INTEGRATION', 'Pending Apns Integration'), ('PENDING', 'Pending'), ('RETRY', 'Retry'), ('WAITING_FOR_DEVICES', 'Waiting For Devices'), ('ACCEPTED_BY_APNS', 'Accepted By Apns'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired')], default='PENDING_APNS_INTEGRATION', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='notificationevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_APNS_INTEGRATION', 'PENDING', 'RETRY', 'WAITING_FOR_DEVICES', 'ACCEPTED_BY_APNS', 'PARTIAL', 'FAILED', 'SKIPPED', 'EXPIRED'])), name='notification_valid_status'),
        ),
        migrations.AddField(
            model_name='pushdelivery',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.pushdevice'),
        ),
        migrations.AddField(
            model_name='pushdelivery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.notificationevent'),
        ),
        migrations.AddField(
            model_name='pushattempt',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='core.pushdelivery'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='push_delivery_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'device', 'device_revision'), name='one_delivery_per_device_revision'),
        ),
        migrations.AddConstraint(
            model_name='pushattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'number'), name='one_number_per_push_attempt'),
        ),
    ]
