# Generated by Django 6.1.1 on 2026-10-06 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_apns_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='development_dashboard_access',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='accountprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('development_dashboard_access', True)), fields=('development_dashboard_access',), name='one_development_dashboard_account'),
        ),
    ]
