"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kx)s*d70@gfycqk+o%ev&v-ilmu359j+b*%3x-^apxo^o59l#%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'rest_framework.authtoken'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# API access is authenticated by default; only login opts out.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['core.api_access.ExpiringTokenAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['core.api_access.CompanyAccountPermission'],
    'EXCEPTION_HANDLER': 'core.api_access.exception_handler',
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
}


# GPS presence is computed from both fix age and receipt age, in seconds.
GPS_ONLINE_SECONDS = int(os.environ.get('GPS_ONLINE_SECONDS', '60'))
GPS_OFFLINE_SECONDS = int(os.environ.get('GPS_OFFLINE_SECONDS', '300'))
GPS_MAX_FUTURE_SECONDS = int(os.environ.get('GPS_MAX_FUTURE_SECONDS', '30'))
if not (0 < GPS_ONLINE_SECONDS < GPS_OFFLINE_SECONDS and GPS_MAX_FUTURE_SECONDS >= 0):
    raise ImproperlyConfigured('GPS thresholds must satisfy 0 < online < offline; future tolerance must be non-negative.')

# Registration allowlist only. This setting does not enable delivery or load Apple credentials.
APNS_ALLOWED_TOPICS = [topic.strip() for topic in os.environ.get('APNS_ALLOWED_TOPICS', '').split(',') if topic.strip()]


# Direct APNs is opt-in; worker startup validates credentials before touching events.
APNS_ENABLED = os.environ.get('APNS_ENABLED', '0') == '1'
APNS_TEAM_ID = os.environ.get('APNS_TEAM_ID', '')
APNS_KEY_ID = os.environ.get('APNS_KEY_ID', '')
APNS_PRIVATE_KEY_PATH = os.environ.get('APNS_PRIVATE_KEY_PATH', '')
APNS_MAX_ATTEMPTS = int(os.environ.get('APNS_MAX_ATTEMPTS', '5'))
APNS_EVENT_TTL_SECONDS = int(os.environ.get('APNS_EVENT_TTL_SECONDS', '3600'))
APNS_REQUEST_TIMEOUT_SECONDS = int(os.environ.get('APNS_REQUEST_TIMEOUT_SECONDS', '10'))
APNS_LEASE_SECONDS = int(os.environ.get('APNS_LEASE_SECONDS', '120'))
if not (APNS_MAX_ATTEMPTS > 0 and APNS_EVENT_TTL_SECONDS > 0 and APNS_REQUEST_TIMEOUT_SECONDS > 0 and APNS_LEASE_SECONDS > APNS_REQUEST_TIMEOUT_SECONDS):
    raise ImproperlyConfigured('APNs limits must be positive and its lease longer than the request timeout.')
